// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cost.proto

#include "cost.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace example_proto_class {
class Computer_CostDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Computer_Cost>
      _instance;
} _Computer_Cost_default_instance_;
class CPU_CostDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CPU_Cost>
      _instance;
} _CPU_Cost_default_instance_;
class Monitor_CostDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Monitor_Cost>
      _instance;
} _Monitor_Cost_default_instance_;
class Interface_CostDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Interface_Cost>
      _instance;
} _Interface_Cost_default_instance_;
}  // namespace example_proto_class
namespace protobuf_cost_2eproto {
void InitDefaultsComputer_CostImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_cost_2eproto::InitDefaultsCPU_Cost();
  protobuf_cost_2eproto::InitDefaultsMonitor_Cost();
  protobuf_cost_2eproto::InitDefaultsInterface_Cost();
  {
    void* ptr = &::example_proto_class::_Computer_Cost_default_instance_;
    new (ptr) ::example_proto_class::Computer_Cost();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example_proto_class::Computer_Cost::InitAsDefaultInstance();
}

void InitDefaultsComputer_Cost() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsComputer_CostImpl);
}

void InitDefaultsCPU_CostImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::example_proto_class::_CPU_Cost_default_instance_;
    new (ptr) ::example_proto_class::CPU_Cost();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example_proto_class::CPU_Cost::InitAsDefaultInstance();
}

void InitDefaultsCPU_Cost() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCPU_CostImpl);
}

void InitDefaultsMonitor_CostImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::example_proto_class::_Monitor_Cost_default_instance_;
    new (ptr) ::example_proto_class::Monitor_Cost();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example_proto_class::Monitor_Cost::InitAsDefaultInstance();
}

void InitDefaultsMonitor_Cost() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMonitor_CostImpl);
}

void InitDefaultsInterface_CostImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::example_proto_class::_Interface_Cost_default_instance_;
    new (ptr) ::example_proto_class::Interface_Cost();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example_proto_class::Interface_Cost::InitAsDefaultInstance();
}

void InitDefaultsInterface_Cost() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsInterface_CostImpl);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Computer_Cost, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Computer_Cost, cpu_cost_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Computer_Cost, mon_cost_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Computer_Cost, in_cost_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Computer_Cost, brand_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::CPU_Cost, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::CPU_Cost, cost_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Monitor_Cost, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Monitor_Cost, cost_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Interface_Cost, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example_proto_class::Interface_Cost, cost_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::example_proto_class::Computer_Cost)},
  { 9, -1, sizeof(::example_proto_class::CPU_Cost)},
  { 15, -1, sizeof(::example_proto_class::Monitor_Cost)},
  { 21, -1, sizeof(::example_proto_class::Interface_Cost)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::example_proto_class::_Computer_Cost_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::example_proto_class::_CPU_Cost_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::example_proto_class::_Monitor_Cost_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::example_proto_class::_Interface_Cost_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cost.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ncost.proto\022\023example_proto_class\"\272\001\n\rCo"
      "mputer_Cost\022/\n\010cpu_cost\030\001 \001(\0132\035.example_"
      "proto_class.CPU_Cost\0223\n\010mon_cost\030\002 \001(\0132!"
      ".example_proto_class.Monitor_Cost\0224\n\007in_"
      "cost\030\003 \001(\0132#.example_proto_class.Interfa"
      "ce_Cost\022\r\n\005brand\030\004 \001(\t\"\030\n\010CPU_Cost\022\014\n\004co"
      "st\030\001 \001(\005\"\034\n\014Monitor_Cost\022\014\n\004cost\030\001 \001(\005\"\036"
      "\n\016Interface_Cost\022\014\n\004cost\030\001 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 318);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cost.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_cost_2eproto
namespace example_proto_class {

// ===================================================================

void Computer_Cost::InitAsDefaultInstance() {
  ::example_proto_class::_Computer_Cost_default_instance_._instance.get_mutable()->cpu_cost_ = const_cast< ::example_proto_class::CPU_Cost*>(
      ::example_proto_class::CPU_Cost::internal_default_instance());
  ::example_proto_class::_Computer_Cost_default_instance_._instance.get_mutable()->mon_cost_ = const_cast< ::example_proto_class::Monitor_Cost*>(
      ::example_proto_class::Monitor_Cost::internal_default_instance());
  ::example_proto_class::_Computer_Cost_default_instance_._instance.get_mutable()->in_cost_ = const_cast< ::example_proto_class::Interface_Cost*>(
      ::example_proto_class::Interface_Cost::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Computer_Cost::kCpuCostFieldNumber;
const int Computer_Cost::kMonCostFieldNumber;
const int Computer_Cost::kInCostFieldNumber;
const int Computer_Cost::kBrandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Computer_Cost::Computer_Cost()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_cost_2eproto::InitDefaultsComputer_Cost();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:example_proto_class.Computer_Cost)
}
Computer_Cost::Computer_Cost(const Computer_Cost& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  brand_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.brand().size() > 0) {
    brand_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brand_);
  }
  if (from.has_cpu_cost()) {
    cpu_cost_ = new ::example_proto_class::CPU_Cost(*from.cpu_cost_);
  } else {
    cpu_cost_ = NULL;
  }
  if (from.has_mon_cost()) {
    mon_cost_ = new ::example_proto_class::Monitor_Cost(*from.mon_cost_);
  } else {
    mon_cost_ = NULL;
  }
  if (from.has_in_cost()) {
    in_cost_ = new ::example_proto_class::Interface_Cost(*from.in_cost_);
  } else {
    in_cost_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:example_proto_class.Computer_Cost)
}

void Computer_Cost::SharedCtor() {
  brand_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&cpu_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&in_cost_) -
      reinterpret_cast<char*>(&cpu_cost_)) + sizeof(in_cost_));
  _cached_size_ = 0;
}

Computer_Cost::~Computer_Cost() {
  // @@protoc_insertion_point(destructor:example_proto_class.Computer_Cost)
  SharedDtor();
}

void Computer_Cost::SharedDtor() {
  brand_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete cpu_cost_;
  if (this != internal_default_instance()) delete mon_cost_;
  if (this != internal_default_instance()) delete in_cost_;
}

void Computer_Cost::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Computer_Cost::descriptor() {
  ::protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Computer_Cost& Computer_Cost::default_instance() {
  ::protobuf_cost_2eproto::InitDefaultsComputer_Cost();
  return *internal_default_instance();
}

Computer_Cost* Computer_Cost::New(::google::protobuf::Arena* arena) const {
  Computer_Cost* n = new Computer_Cost;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Computer_Cost::Clear() {
// @@protoc_insertion_point(message_clear_start:example_proto_class.Computer_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  brand_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && cpu_cost_ != NULL) {
    delete cpu_cost_;
  }
  cpu_cost_ = NULL;
  if (GetArenaNoVirtual() == NULL && mon_cost_ != NULL) {
    delete mon_cost_;
  }
  mon_cost_ = NULL;
  if (GetArenaNoVirtual() == NULL && in_cost_ != NULL) {
    delete in_cost_;
  }
  in_cost_ = NULL;
  _internal_metadata_.Clear();
}

bool Computer_Cost::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example_proto_class.Computer_Cost)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .example_proto_class.CPU_Cost cpu_cost = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_cpu_cost()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .example_proto_class.Monitor_Cost mon_cost = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_mon_cost()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .example_proto_class.Interface_Cost in_cost = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_in_cost()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string brand = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_brand()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->brand().data(), static_cast<int>(this->brand().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "example_proto_class.Computer_Cost.brand"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example_proto_class.Computer_Cost)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example_proto_class.Computer_Cost)
  return false;
#undef DO_
}

void Computer_Cost::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example_proto_class.Computer_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .example_proto_class.CPU_Cost cpu_cost = 1;
  if (this->has_cpu_cost()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->cpu_cost_, output);
  }

  // .example_proto_class.Monitor_Cost mon_cost = 2;
  if (this->has_mon_cost()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->mon_cost_, output);
  }

  // .example_proto_class.Interface_Cost in_cost = 3;
  if (this->has_in_cost()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->in_cost_, output);
  }

  // string brand = 4;
  if (this->brand().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brand().data(), static_cast<int>(this->brand().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "example_proto_class.Computer_Cost.brand");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->brand(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:example_proto_class.Computer_Cost)
}

::google::protobuf::uint8* Computer_Cost::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:example_proto_class.Computer_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .example_proto_class.CPU_Cost cpu_cost = 1;
  if (this->has_cpu_cost()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->cpu_cost_, deterministic, target);
  }

  // .example_proto_class.Monitor_Cost mon_cost = 2;
  if (this->has_mon_cost()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->mon_cost_, deterministic, target);
  }

  // .example_proto_class.Interface_Cost in_cost = 3;
  if (this->has_in_cost()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *this->in_cost_, deterministic, target);
  }

  // string brand = 4;
  if (this->brand().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brand().data(), static_cast<int>(this->brand().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "example_proto_class.Computer_Cost.brand");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->brand(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example_proto_class.Computer_Cost)
  return target;
}

size_t Computer_Cost::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example_proto_class.Computer_Cost)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string brand = 4;
  if (this->brand().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->brand());
  }

  // .example_proto_class.CPU_Cost cpu_cost = 1;
  if (this->has_cpu_cost()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->cpu_cost_);
  }

  // .example_proto_class.Monitor_Cost mon_cost = 2;
  if (this->has_mon_cost()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->mon_cost_);
  }

  // .example_proto_class.Interface_Cost in_cost = 3;
  if (this->has_in_cost()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->in_cost_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Computer_Cost::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example_proto_class.Computer_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  const Computer_Cost* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Computer_Cost>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example_proto_class.Computer_Cost)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example_proto_class.Computer_Cost)
    MergeFrom(*source);
  }
}

void Computer_Cost::MergeFrom(const Computer_Cost& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example_proto_class.Computer_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.brand().size() > 0) {

    brand_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brand_);
  }
  if (from.has_cpu_cost()) {
    mutable_cpu_cost()->::example_proto_class::CPU_Cost::MergeFrom(from.cpu_cost());
  }
  if (from.has_mon_cost()) {
    mutable_mon_cost()->::example_proto_class::Monitor_Cost::MergeFrom(from.mon_cost());
  }
  if (from.has_in_cost()) {
    mutable_in_cost()->::example_proto_class::Interface_Cost::MergeFrom(from.in_cost());
  }
}

void Computer_Cost::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example_proto_class.Computer_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Computer_Cost::CopyFrom(const Computer_Cost& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example_proto_class.Computer_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Computer_Cost::IsInitialized() const {
  return true;
}

void Computer_Cost::Swap(Computer_Cost* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Computer_Cost::InternalSwap(Computer_Cost* other) {
  using std::swap;
  brand_.Swap(&other->brand_);
  swap(cpu_cost_, other->cpu_cost_);
  swap(mon_cost_, other->mon_cost_);
  swap(in_cost_, other->in_cost_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Computer_Cost::GetMetadata() const {
  protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CPU_Cost::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CPU_Cost::kCostFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CPU_Cost::CPU_Cost()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_cost_2eproto::InitDefaultsCPU_Cost();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:example_proto_class.CPU_Cost)
}
CPU_Cost::CPU_Cost(const CPU_Cost& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cost_ = from.cost_;
  // @@protoc_insertion_point(copy_constructor:example_proto_class.CPU_Cost)
}

void CPU_Cost::SharedCtor() {
  cost_ = 0;
  _cached_size_ = 0;
}

CPU_Cost::~CPU_Cost() {
  // @@protoc_insertion_point(destructor:example_proto_class.CPU_Cost)
  SharedDtor();
}

void CPU_Cost::SharedDtor() {
}

void CPU_Cost::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CPU_Cost::descriptor() {
  ::protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CPU_Cost& CPU_Cost::default_instance() {
  ::protobuf_cost_2eproto::InitDefaultsCPU_Cost();
  return *internal_default_instance();
}

CPU_Cost* CPU_Cost::New(::google::protobuf::Arena* arena) const {
  CPU_Cost* n = new CPU_Cost;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CPU_Cost::Clear() {
// @@protoc_insertion_point(message_clear_start:example_proto_class.CPU_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cost_ = 0;
  _internal_metadata_.Clear();
}

bool CPU_Cost::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example_proto_class.CPU_Cost)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 cost = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cost_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example_proto_class.CPU_Cost)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example_proto_class.CPU_Cost)
  return false;
#undef DO_
}

void CPU_Cost::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example_proto_class.CPU_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cost = 1;
  if (this->cost() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cost(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:example_proto_class.CPU_Cost)
}

::google::protobuf::uint8* CPU_Cost::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:example_proto_class.CPU_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cost = 1;
  if (this->cost() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cost(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example_proto_class.CPU_Cost)
  return target;
}

size_t CPU_Cost::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example_proto_class.CPU_Cost)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 cost = 1;
  if (this->cost() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cost());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CPU_Cost::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example_proto_class.CPU_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  const CPU_Cost* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CPU_Cost>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example_proto_class.CPU_Cost)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example_proto_class.CPU_Cost)
    MergeFrom(*source);
  }
}

void CPU_Cost::MergeFrom(const CPU_Cost& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example_proto_class.CPU_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cost() != 0) {
    set_cost(from.cost());
  }
}

void CPU_Cost::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example_proto_class.CPU_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CPU_Cost::CopyFrom(const CPU_Cost& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example_proto_class.CPU_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CPU_Cost::IsInitialized() const {
  return true;
}

void CPU_Cost::Swap(CPU_Cost* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CPU_Cost::InternalSwap(CPU_Cost* other) {
  using std::swap;
  swap(cost_, other->cost_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CPU_Cost::GetMetadata() const {
  protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Monitor_Cost::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Monitor_Cost::kCostFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Monitor_Cost::Monitor_Cost()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_cost_2eproto::InitDefaultsMonitor_Cost();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:example_proto_class.Monitor_Cost)
}
Monitor_Cost::Monitor_Cost(const Monitor_Cost& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cost_ = from.cost_;
  // @@protoc_insertion_point(copy_constructor:example_proto_class.Monitor_Cost)
}

void Monitor_Cost::SharedCtor() {
  cost_ = 0;
  _cached_size_ = 0;
}

Monitor_Cost::~Monitor_Cost() {
  // @@protoc_insertion_point(destructor:example_proto_class.Monitor_Cost)
  SharedDtor();
}

void Monitor_Cost::SharedDtor() {
}

void Monitor_Cost::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Monitor_Cost::descriptor() {
  ::protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Monitor_Cost& Monitor_Cost::default_instance() {
  ::protobuf_cost_2eproto::InitDefaultsMonitor_Cost();
  return *internal_default_instance();
}

Monitor_Cost* Monitor_Cost::New(::google::protobuf::Arena* arena) const {
  Monitor_Cost* n = new Monitor_Cost;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Monitor_Cost::Clear() {
// @@protoc_insertion_point(message_clear_start:example_proto_class.Monitor_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cost_ = 0;
  _internal_metadata_.Clear();
}

bool Monitor_Cost::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example_proto_class.Monitor_Cost)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 cost = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cost_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example_proto_class.Monitor_Cost)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example_proto_class.Monitor_Cost)
  return false;
#undef DO_
}

void Monitor_Cost::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example_proto_class.Monitor_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cost = 1;
  if (this->cost() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cost(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:example_proto_class.Monitor_Cost)
}

::google::protobuf::uint8* Monitor_Cost::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:example_proto_class.Monitor_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cost = 1;
  if (this->cost() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cost(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example_proto_class.Monitor_Cost)
  return target;
}

size_t Monitor_Cost::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example_proto_class.Monitor_Cost)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 cost = 1;
  if (this->cost() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cost());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Monitor_Cost::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example_proto_class.Monitor_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  const Monitor_Cost* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Monitor_Cost>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example_proto_class.Monitor_Cost)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example_proto_class.Monitor_Cost)
    MergeFrom(*source);
  }
}

void Monitor_Cost::MergeFrom(const Monitor_Cost& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example_proto_class.Monitor_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cost() != 0) {
    set_cost(from.cost());
  }
}

void Monitor_Cost::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example_proto_class.Monitor_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Monitor_Cost::CopyFrom(const Monitor_Cost& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example_proto_class.Monitor_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Monitor_Cost::IsInitialized() const {
  return true;
}

void Monitor_Cost::Swap(Monitor_Cost* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Monitor_Cost::InternalSwap(Monitor_Cost* other) {
  using std::swap;
  swap(cost_, other->cost_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Monitor_Cost::GetMetadata() const {
  protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Interface_Cost::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Interface_Cost::kCostFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Interface_Cost::Interface_Cost()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_cost_2eproto::InitDefaultsInterface_Cost();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:example_proto_class.Interface_Cost)
}
Interface_Cost::Interface_Cost(const Interface_Cost& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cost_ = from.cost_;
  // @@protoc_insertion_point(copy_constructor:example_proto_class.Interface_Cost)
}

void Interface_Cost::SharedCtor() {
  cost_ = 0;
  _cached_size_ = 0;
}

Interface_Cost::~Interface_Cost() {
  // @@protoc_insertion_point(destructor:example_proto_class.Interface_Cost)
  SharedDtor();
}

void Interface_Cost::SharedDtor() {
}

void Interface_Cost::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Interface_Cost::descriptor() {
  ::protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Interface_Cost& Interface_Cost::default_instance() {
  ::protobuf_cost_2eproto::InitDefaultsInterface_Cost();
  return *internal_default_instance();
}

Interface_Cost* Interface_Cost::New(::google::protobuf::Arena* arena) const {
  Interface_Cost* n = new Interface_Cost;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Interface_Cost::Clear() {
// @@protoc_insertion_point(message_clear_start:example_proto_class.Interface_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cost_ = 0;
  _internal_metadata_.Clear();
}

bool Interface_Cost::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example_proto_class.Interface_Cost)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 cost = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cost_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example_proto_class.Interface_Cost)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example_proto_class.Interface_Cost)
  return false;
#undef DO_
}

void Interface_Cost::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example_proto_class.Interface_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cost = 1;
  if (this->cost() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cost(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:example_proto_class.Interface_Cost)
}

::google::protobuf::uint8* Interface_Cost::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:example_proto_class.Interface_Cost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cost = 1;
  if (this->cost() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cost(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example_proto_class.Interface_Cost)
  return target;
}

size_t Interface_Cost::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example_proto_class.Interface_Cost)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 cost = 1;
  if (this->cost() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cost());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Interface_Cost::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example_proto_class.Interface_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  const Interface_Cost* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Interface_Cost>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example_proto_class.Interface_Cost)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example_proto_class.Interface_Cost)
    MergeFrom(*source);
  }
}

void Interface_Cost::MergeFrom(const Interface_Cost& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example_proto_class.Interface_Cost)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cost() != 0) {
    set_cost(from.cost());
  }
}

void Interface_Cost::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example_proto_class.Interface_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Interface_Cost::CopyFrom(const Interface_Cost& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example_proto_class.Interface_Cost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Interface_Cost::IsInitialized() const {
  return true;
}

void Interface_Cost::Swap(Interface_Cost* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Interface_Cost::InternalSwap(Interface_Cost* other) {
  using std::swap;
  swap(cost_, other->cost_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Interface_Cost::GetMetadata() const {
  protobuf_cost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace example_proto_class

// @@protoc_insertion_point(global_scope)
