# Bazel build file workspace, required protoc and c++ protobuf runtime

# It provides the protocol compiler binary (i.e., protoc)
http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/google/protobuf/archive/master.zip"],
)
load("@com_google_protobuf//:protobuf.bzl", "check_protobuf_required_bazel_version")
check_protobuf_required_bazel_version()

# This com_google_protobuf_cc repository is required for cc_proto_library
# rule. It provides protobuf C++ runtime.
http_archive(
    name = "com_google_protobuf_cc",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/google/protobuf/archive/master.zip"],
)
