cc_library(
    name = "libtensorflow",
    srcs = ["libtensorflow.so.1", "libtensorflow_framework.so.1"],
    hdrs = ["c_api.h", "tf_attrtype.h",
            "tf_datatype.h", "tf_status.h"],
    copts = ["-Ilibs"],
    visibility = ["//visibility:public"],
)
